spring:
  config:
    import: application-secret.yml

  jpa:
    hibernate:
      ddl-auto: none   # 개발 중에는 create / create-drop / update 중 선택
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB       # 파일 1개 최대 5MB
      max-request-size: 50MB   # 한 요청 최대(최대 10개 업로드, 총 50MB)

logging:
  level:
    org.hibernate.SQL: debug
    root: debug
    
# 이미지 정책 설정
image:
  max-size-bytes: 5242880         # 5MB
  max-per-post: 10                # 게시글당 최대 이미지 개수
  allowed-extensions:             # 허용 확장자
    - jpeg
    - jpg
    - png
    - gif
    - webp
  profile-path-format: "user/%d/profile/%s" # 경로 포맷 (String.format)
  post-path-format: "post/%d/images/%s"     # 경로 포맷 (String.format)

# 이메일 설정
email:
  password-reset:
    min-interval-ms: 60000  # 비밀번호 재설정 인증번호 발송 최소 간격 (밀리초)
    code-expiration-minutes: 10  # 인증번호 유효 시간 (분)

# AWS S3 설정
aws:
  s3:
    bucket-name: community-images-857597738766
    region: ap-northeast-2
    presigned-url-expiration-minutes: 5